apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
type: Opaque
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.auth.erlangCookie | b64enc | quote }}