name: faculty-hours-broker
services:
  rabbitmq:
    build: 
      context: ..
      dockerfile: ./.docker/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - faculty_network
      - common_network
    env_file:
      - .env

networks:
  faculty_network:
    driver: bridge
  common_network:
    external: true